sudo: required
dist: trusty
language: node_js
node_js: 8
install:
  - "npm install"
  - "npm install truffle"
  - "npm install ganache-cli"
  - "npm run ganache-cli > /dev/null &"
script:
  - "ganache-cli -p 7545 > /dev/null &"
  - "sleep 5"
  - "npm run test"
  