sudo: required
dist: trusty
language: node_js
node_js: 8
install:
  - "npm install"
  - "npm install truffle —save"
  - "npm install ganache-cli —save"
  - "npm run ganache-cli > /dev/null &"
script:
  - "npm run test"
  