# sudo: required
# dist: trusty
# language: node_js
# node_js: 8
# install:
#   - "npm install"
#   - "npm run ganache-cli > /dev/null &"
# script:
#   - "npm run test"


sudo: required
dist: trusty
language: node_js
node_js: 8
install:
  - "npm install"
  - "npm run testrpc > /dev/null &"
script:
  - "npm run test"